**Artur Kompała - Lab 2**


Ćwiczenie 1:
Z podanego zbioru danych wypisz  pierwsze i ostatnie pięć wierszy

In [91]:
import pandas as pd
df_auto = pd.read_csv('data/Automobile_data.csv')

idx = list(df_auto.head(5).index) + list(df_auto.tail(5).index)
df_auto.loc[idx]

index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage  price  
0              four         111               21  13495  
1              four         111               21  16500  
2               six         154               19  16500  
3              four         102               24  13950  
4              five         115               18  17450  
56             four          85               27   7975  
57             four          52               37   7995  
58             four         100               26   9995  
59             four         114               23  12940  
60             four         114               23  13415

Ćwiczenie 2:
Wyczyść zbiór danych i zaktualizuj plik CSV
Zastąp wszystkie wartości kolumn zawierające ?, N.a lub NaN.

In [92]:
df_clean = df_auto.replace(['?', 'N.a', 'NaN'], pd.NA)
df_clean = df_clean.fillna(0)
df_clean['price'] = pd.to_numeric(df_clean['price'], errors='coerce').fillna(0)
df_clean.to_csv('data/Automobile_data_cleaned.csv', index=False)
print(df_clean.isnull().sum())
print(df_clean['price'].dtype)


index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               0
dtype: int64
int64


Ćwiczenie 3:
Znajdź nazwę najdroższej firmy samochodowej
Wydrukuj nazwę firmy i cenę najdroższych samochodów.

In [93]:
print("Najdroższa firma samochodowa:")
print(df_clean.groupby('company')['price'].mean().sort_values(ascending=False).head(1))
print("Top 3 Najdroższe samochody:")
print(df_clean.sort_values(by=['price'], ascending=False).head(3))

Najdroższa firma samochodowa:
company
mercedes-benz    35040.0
Name: price, dtype: float64
Top 3 Najdroższe samochody:
    index        company body-style  wheel-base  length engine-type  \
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
11     14            bmw      sedan       103.5   193.8         ohc   
34     46  mercedes-benz      sedan       120.9   208.1        ohcv   

   num-of-cylinders  horsepower  average-mileage  price  
35            eight         184               14  45400  
11              six         182               16  41315  
34            eight         184               14  40960  


Ćwiczenie 4:
Wydrukuj wszystkie szczegóły dotyczące samochodów Toyota

In [94]:
df_clean.groupby('company').get_group('toyota')

index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage  price  
48          62               35   5348  
49          62               31   6338  
50          62               31   6488  
51          62               31   6918  
52          62               27   7898  
53          62               27   8778  
54         156               19  15750

Ćwiczenie 5:
Policz wszystkie samochody z podziałem na firmę

In [95]:
df_clean.groupby('company').size()

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
dtype: int64

Ćwiczenie 6:
Znajdź samochód o najwyższej cenie w każdej firmie

In [96]:
df_clean.groupby('company')['price'].max()

company
alfa-romero      16500
audi             18920
bmw              41315
chevrolet         6575
dodge             6377
honda            12945
isuzu             6785
jaguar           36000
mazda            18344
mercedes-benz    45400
mitsubishi        8189
nissan           13499
porsche          37028
toyota           15750
volkswagen        9995
volvo            13415
Name: price, dtype: int64

Ćwiczenie 7:
Znajdź średni przebieg dla każdej firmy produkującej samochody

In [97]:
df_clean.groupby('company')['average-mileage'].mean()

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64

Ćwiczenie 8:
Posortuj wszystkie samochody według kolumny Cena

In [98]:
df_clean.sort_values(['price'], ascending=False)

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
..    ...            ...          ...         ...     ...         ...   
27     36          mazda    hatchback        93.1   159.1         ohc   
13     16      chevrolet    hatchback        88.4   141.1           l   
23     32          isuzu        sedan        94.5   155.9         ohc   
22     31          isuzu        sedan        94.5   155.9         ohc   
47     63        porsche    hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage  price  
35            eight         184               14  45400  
11              six         182               16  41315  
34            eight         184               14  40960  
46              six         207               17  37028  
12              six         182               15  36880  
..              ...         ...              ...    ...  
27             four          68               30   5195  
13            three          48               47   5151  
23             four          70               38      0  
22             four          70               38      0  
47            eight         288               17      0  

[61 rows x 10 columns]

Ćwiczenie 9:
Łączenie dwóch ramek danych
Utwórz dwie ramki danych, korzystając z następujących dwóch słowników.
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [99]:
germanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
pd.concat([pd.DataFrame(germanCars), pd.DataFrame(japaneseCars)], ignore_index=True)


Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

Ćwiczenie 10:
Połącz dwie ramki danych.
Utwórz dwie ramki danych, używając następujących dwóch słowników, następnie połącz dwie ramki
danych - dołącz drugą ramkę danych jako nową kolumnę do pierwszej ramki danych.
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [100]:
car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
pd.merge(pd.DataFrame(car_Price), pd.DataFrame(car_Horsepower))

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

Ćwiczenie 11:
Napisz program, który wybierze losową liczbę wierszy, ze zbioru danych o spożyciu alkoholu na
świecie.

In [101]:
df_alko = pd.read_csv('data/world_alcohol.csv')
df_alko.sample(n=5)

Year WHO region             Country Beverage Types  Display Value
44  1985     Europe           Lithuania          Other            NaN
49  1986     Europe               Malta           Wine           1.49
72  1987     Africa          Mauritania          Other           0.00
78  1989   Americas             Jamaica          Other           0.00
34  1986     Europe  Russian Federation           Wine           0.80

Ćwiczenie 12:
Napisz program, wyświetlający spożycie alkoholu w regionach w konkretnym wskazanym roku.

In [102]:
rok = 1985
df_alko[df_alko['Year'] == rok].groupby('WHO region')['Display Value'].sum()

WHO region
Africa                    3.46
Americas                  2.24
Eastern Mediterranean     0.00
Europe                   14.64
South-East Asia           0.00
Western Pacific           0.05
Name: Display Value, dtype: float64

Ćwiczenie 13:
Napisz program, który zwróci szczegóły dotyczące spożycia alkoholu w „Ameryce” w roku „1985”.

In [103]:
df_alko[(df_alko['Year'] == 1985) & (df_alko['WHO region'] == 'Americas')]

Year WHO region                Country Beverage Types  Display Value
35  1985   Americas  Saint Kitts and Nevis        Spirits           2.24

Ćwiczenie 14:
Napisz program, który zwróci rekordy, w których średnie spożycie napojów alkoholowych na osobę
wynosi> = 5, a rodzaje napoju to piwo

In [104]:
df_alko[(df_alko['Beverage Types'] == 'Beer') & (df_alko['Display Value'] >= 5)]

Year WHO region         Country Beverage Types  Display Value
41  1986     Europe  Czech Republic           Beer           6.82

Ćwiczenie 15
Napisz program, który wyświetli średnie spożycie wina na osobę większe niż 2

In [105]:
df_alko[(df_alko['Beverage Types'] == 'Wine') & (df_alko['Display Value'] > 2)]

Year WHO region      Country Beverage Types  Display Value
57  1989     Europe      Croatia           Wine           5.10
81  1985     Europe  Netherlands           Wine           2.54
96  1985     Europe   Luxembourg           Wine           7.38